### PR TITLE
Dockerfile for hub automated build

### PR DESCRIPTION
**Pull request by macropin**
Also added a `requirements-build.txt` to mitigate build issues with dependency resolution and other pypi shenanigans. 

Refs #6

### CODE REVIEW

**Review by andrey-pohilko — APPROVED** [review]

**Review by andrey-pohilko — APPROVED** [review]

**Comment by andrey-pohilko** [comment]
Thanks for contribution!

**Comment by jonaskello** [comment]
Really nice! But I cannot find the image in docker hub, where is it? (I don't have a python environment but I really want to run this tool)

**Comment by andrey-pohilko** [comment]
At present there is no image on docker hub, you have to build it yourself, and its pretty simple. Just download contents of the folder and run command from this folder:
`docker build -t registry-cli .`

It will create the image "registry-cli" for you to enjoy.

**Comment by jonaskello** [comment]
Ah, I see. I want to use it in my gitlab CI build so a need a pre-built image for the CI runner to use. So a public image at docker hub is the best option for me.

Actually, it is really easy to setup automatic docker builds. Just create an account at dockerhub, create a build, point it to your github repo and you are done :-). It will automatically pick up branch names, tags etc. and do everything for you.

I could fork this repo and do a dockerhub build for it but if you had it officially set up that would of course be better.

**Comment by andrey-pohilko** [comment]
Thanks for the information, I am now working on it

**Comment by andrey-pohilko** [comment]
Hey @jonaskello, please try 

> https://hub.docker.com/r/anoxis/registry-cli/ 

Command to pull it from the hub:
`docker pull  anoxis/registry-cli`

Commands to use are the same as in the readme, just prepend `docker run anoxis/registry-cli` instead of `registry.py`, e.g. to simply list all images inside your registry run:
`docker run anoxis/registry-cli -r https://localhost:5000 -l user:password` 

Please revert back if all is ok, I will update the readme and the description at the hub.

**Comment by jonaskello** [comment]
@andrey-pohilko Big thanks for the quick publish! 🥇 

I can confirm that is is now possible to run it like this (which might be a good example for the readme):

```
docker run --rm anoxis/registry-cli -l user:pass -r http://localhost:5000
```
It will run the command with the arguments and also remove the resulting container afterwards to cleanup.

(However it seems like I'm unable to connect to my registry in gitlab but that is another issue, the command itself runs just fine in the dockerized version).

**Pull request merged**
