### PR TITLE
Fix obtaining access token

### PR DESCRIPTION
**Pull request by fpytloun**

### CODE REVIEW

**Comment by donbowman** [comment]
i found i needed 'token', not 'access_token'.
And I needd to do a .decode('utf-8')

so

`token = ast.literal_eval(try_oauth._content.decode('utf-8'))['token']`

**Comment by karlskewes** [comment]
Thanks for this. I just need to use `'token'` to get a list.
Haven't found need for decode utf-8... yet.

**Comment by donbowman** [comment]
i think on python 3 u need teh decode.

**Comment by andrey-pohilko** [comment]
closed as duplicate of #61

**Pull request closed without merging**
